// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package models

import (
	"context"
	"database/sql"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (team, slug, "name", "order")
VALUES (
        ?1,
        ?2,
        ?3,
        (
            SELECT 1 + IFNULL(MAX("order"), -1)
            FROM players p
            WHERE p.team = ?1
        )
    )
RETURNING id, team, slug, name, "order"
`

type CreatePlayerParams struct {
	Team int64  `db:"team" json:"team"`
	Slug string `db:"slug" json:"slug"`
	Name string `db:"name" json:"name"`
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, createPlayer, arg.Team, arg.Slug, arg.Name)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Team,
		&i.Slug,
		&i.Name,
		&i.Order,
	)
	return i, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams ("owner", "name", "slug", "organization")
VALUES (?, ?, ?, ?)
RETURNING id, owner, name, slug, organization
`

type CreateTeamParams struct {
	Owner        int64          `db:"owner" json:"owner"`
	Name         string         `db:"name" json:"name"`
	Slug         string         `db:"slug" json:"slug"`
	Organization sql.NullString `db:"organization" json:"organization"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, createTeam,
		arg.Owner,
		arg.Name,
		arg.Slug,
		arg.Organization,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Name,
		&i.Slug,
		&i.Organization,
	)
	return i, err
}

const createTournament = `-- name: CreateTournament :one
INSERT INTO tournaments (team, "name", slug)
VALUES (?, ?, ?)
RETURNING id, team, name, slug, start_date, end_date, location
`

type CreateTournamentParams struct {
	TeamId int64  `db:"teamId" json:"teamId"`
	Name   string `db:"name" json:"name"`
	Slug   string `db:"slug" json:"slug"`
}

func (q *Queries) CreateTournament(ctx context.Context, arg CreateTournamentParams) (Tournament, error) {
	row := q.db.QueryRowContext(ctx, createTournament, arg.TeamId, arg.Name, arg.Slug)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.Team,
		&i.Name,
		&i.Slug,
		&i.StartDate,
		&i.EndDate,
		&i.Location,
	)
	return i, err
}

const createTournamentDatum = `-- name: CreateTournamentDatum :one
INSERT INTO tournament_data (tournament, "order")
VALUES (
        ?1,
        (
            SELECT 1 + IFNULL(MAX("order"), -1)
            FROM tournament_data
            WHERE tournament = ?1
        )
    )
RETURNING id, tournament, icon, title, show_in_preview, text_preview, data_type, value_text, value_link, "order"
`

func (q *Queries) CreateTournamentDatum(ctx context.Context, tournamentid int64) (TournamentDatum, error) {
	row := q.db.QueryRowContext(ctx, createTournamentDatum, tournamentid)
	var i TournamentDatum
	err := row.Scan(
		&i.ID,
		&i.Tournament,
		&i.Icon,
		&i.Title,
		&i.ShowInPreview,
		&i.TextPreview,
		&i.DataType,
		&i.ValueText,
		&i.ValueLink,
		&i.Order,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash)
VALUES (LOWER(?), ?)
RETURNING id, email, password_hash
`

type CreateUserParams struct {
	Email        string         `db:"email" json:"email"`
	PasswordHash sql.NullString `db:"password_hash" json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.PasswordHash)
	return i, err
}

const getPlayer = `-- name: GetPlayer :one
SELECT id, team, slug, name, "order"
FROM players
WHERE team = ?1
    AND slug = ?2
`

type GetPlayerParams struct {
	TeamId int64  `db:"teamId" json:"teamId"`
	Slug   string `db:"slug" json:"slug"`
}

func (q *Queries) GetPlayer(ctx context.Context, arg GetPlayerParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayer, arg.TeamId, arg.Slug)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Team,
		&i.Slug,
		&i.Name,
		&i.Order,
	)
	return i, err
}

const getTeam = `-- name: GetTeam :one
SELECT id, owner, name, slug, organization
FROM teams
WHERE slug = LOWER(?1)
`

func (q *Queries) GetTeam(ctx context.Context, slug string) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeam, slug)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Name,
		&i.Slug,
		&i.Organization,
	)
	return i, err
}

const getTournament = `-- name: GetTournament :one
SELECT id, team, name, slug, start_date, end_date, location
FROM tournaments
WHERE team = ?1
    AND slug = ?2
`

type GetTournamentParams struct {
	TeamId int64  `db:"teamId" json:"teamId"`
	Slug   string `db:"slug" json:"slug"`
}

func (q *Queries) GetTournament(ctx context.Context, arg GetTournamentParams) (Tournament, error) {
	row := q.db.QueryRowContext(ctx, getTournament, arg.TeamId, arg.Slug)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.Team,
		&i.Name,
		&i.Slug,
		&i.StartDate,
		&i.EndDate,
		&i.Location,
	)
	return i, err
}

const getTournamentDatum = `-- name: GetTournamentDatum :one
SELECT id, tournament, icon, title, show_in_preview, text_preview, data_type, value_text, value_link, "order"
FROM tournament_data
WHERE id = ?1
    AND tournament = ?2
`

type GetTournamentDatumParams struct {
	DataId       int64 `db:"dataId" json:"dataId"`
	TournamentId int64 `db:"tournamentId" json:"tournamentId"`
}

func (q *Queries) GetTournamentDatum(ctx context.Context, arg GetTournamentDatumParams) (TournamentDatum, error) {
	row := q.db.QueryRowContext(ctx, getTournamentDatum, arg.DataId, arg.TournamentId)
	var i TournamentDatum
	err := row.Scan(
		&i.ID,
		&i.Tournament,
		&i.Icon,
		&i.Title,
		&i.ShowInPreview,
		&i.TextPreview,
		&i.DataType,
		&i.ValueText,
		&i.ValueLink,
		&i.Order,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, password_hash
FROM users
WHERE email = LOWER(?1)
`

func (q *Queries) GetUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, email)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.PasswordHash)
	return i, err
}

const listFollowedTeams = `-- name: ListFollowedTeams :many
SELECT t.id, t.owner, t.name, t.slug, t.organization
FROM team_follow tf
    INNER JOIN teams t ON t.id = tf.team
WHERE tf.user = ?1
ORDER BY t.name ASC
`

func (q *Queries) ListFollowedTeams(ctx context.Context, userid int64) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, listFollowedTeams, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Name,
			&i.Slug,
			&i.Organization,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnedTeams = `-- name: ListOwnedTeams :many
SELECT id, owner, name, slug, organization
FROM teams
WHERE teams.owner = ?1
ORDER BY id DESC
`

func (q *Queries) ListOwnedTeams(ctx context.Context, userid int64) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, listOwnedTeams, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Name,
			&i.Slug,
			&i.Organization,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamGames = `-- name: ListTeamGames :many
SELECT g.id, g.tournament, g.slug, g.opponent, g.schedule_status, g.start, g.start_timezone, g.wind, g."temp", g.half_cap, g.soft_cap, g.hard_cap
FROM games g
INNER JOIN tournaments t
WHERE t.team = ?1
ORDER BY g.start ASC
`

func (q *Queries) ListTeamGames(ctx context.Context, teamid int64) ([]Game, error) {
	rows, err := q.db.QueryContext(ctx, listTeamGames, teamid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Tournament,
			&i.Slug,
			&i.Opponent,
			&i.ScheduleStatus,
			&i.Start,
			&i.StartTimezone,
			&i.Wind,
			&i.Temp,
			&i.HalfCap,
			&i.SoftCap,
			&i.HardCap,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamPlayers = `-- name: ListTeamPlayers :many
SELECT id, team, slug, name, "order"
FROM players
WHERE team = ?1
ORDER BY "order" ASC
`

func (q *Queries) ListTeamPlayers(ctx context.Context, teamid int64) ([]Player, error) {
	rows, err := q.db.QueryContext(ctx, listTeamPlayers, teamid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.Team,
			&i.Slug,
			&i.Name,
			&i.Order,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamTournamentData = `-- name: ListTeamTournamentData :many
SELECT td.id, td.tournament, td.icon, td.title, td.show_in_preview, td.text_preview, td.data_type, td.value_text, td.value_link, td."order"
FROM tournament_data td
INNER JOIN tournaments t
WHERE t.team = ?1
ORDER BY td."order" ASC
`

func (q *Queries) ListTeamTournamentData(ctx context.Context, teamid int64) ([]TournamentDatum, error) {
	rows, err := q.db.QueryContext(ctx, listTeamTournamentData, teamid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TournamentDatum
	for rows.Next() {
		var i TournamentDatum
		if err := rows.Scan(
			&i.ID,
			&i.Tournament,
			&i.Icon,
			&i.Title,
			&i.ShowInPreview,
			&i.TextPreview,
			&i.DataType,
			&i.ValueText,
			&i.ValueLink,
			&i.Order,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTournamentData = `-- name: ListTournamentData :many
SELECT id, tournament, icon, title, show_in_preview, text_preview, data_type, value_text, value_link, "order"
FROM tournament_data
WHERE tournament = ?1
ORDER BY "order" ASC
`

func (q *Queries) ListTournamentData(ctx context.Context, tournamentid int64) ([]TournamentDatum, error) {
	rows, err := q.db.QueryContext(ctx, listTournamentData, tournamentid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TournamentDatum
	for rows.Next() {
		var i TournamentDatum
		if err := rows.Scan(
			&i.ID,
			&i.Tournament,
			&i.Icon,
			&i.Title,
			&i.ShowInPreview,
			&i.TextPreview,
			&i.DataType,
			&i.ValueText,
			&i.ValueLink,
			&i.Order,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTournaments = `-- name: ListTournaments :many
SELECT id, team, name, slug, start_date, end_date, location
FROM tournaments
WHERE team = ?1
ORDER BY "start_date" ASC,
    id ASC
`

func (q *Queries) ListTournaments(ctx context.Context, teamid int64) ([]Tournament, error) {
	rows, err := q.db.QueryContext(ctx, listTournaments, teamid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tournament
	for rows.Next() {
		var i Tournament
		if err := rows.Scan(
			&i.ID,
			&i.Team,
			&i.Name,
			&i.Slug,
			&i.StartDate,
			&i.EndDate,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlayer = `-- name: UpdatePlayer :one
UPDATE players
SET "name" = ?,
    slug = ?
WHERE id = ?
RETURNING id, team, slug, name, "order"
`

type UpdatePlayerParams struct {
	Name string `db:"name" json:"name"`
	Slug string `db:"slug" json:"slug"`
	ID   int64  `db:"id" json:"id"`
}

func (q *Queries) UpdatePlayer(ctx context.Context, arg UpdatePlayerParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, updatePlayer, arg.Name, arg.Slug, arg.ID)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Team,
		&i.Slug,
		&i.Name,
		&i.Order,
	)
	return i, err
}

const updatePlayerOrder = `-- name: UpdatePlayerOrder :exec
UPDATE players
SET "order" = ?
WHERE id = ?
    AND team = ?
`

type UpdatePlayerOrderParams struct {
	Order int64 `db:"order" json:"order"`
	ID    int64 `db:"id" json:"id"`
	Team  int64 `db:"team" json:"team"`
}

func (q *Queries) UpdatePlayerOrder(ctx context.Context, arg UpdatePlayerOrderParams) error {
	_, err := q.db.ExecContext(ctx, updatePlayerOrder, arg.Order, arg.ID, arg.Team)
	return err
}

const updateTeamName = `-- name: UpdateTeamName :one
UPDATE teams
SET "name" = ?,
    "slug" = ?
WHERE teams.slug = ?
RETURNING id, owner, name, slug, organization
`

type UpdateTeamNameParams struct {
	Name    string `db:"name" json:"name"`
	NewSlug string `db:"newSlug" json:"newSlug"`
	OldSlug string `db:"oldSlug" json:"oldSlug"`
}

func (q *Queries) UpdateTeamName(ctx context.Context, arg UpdateTeamNameParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, updateTeamName, arg.Name, arg.NewSlug, arg.OldSlug)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Name,
		&i.Slug,
		&i.Organization,
	)
	return i, err
}

const updateTeamOrganization = `-- name: UpdateTeamOrganization :one
UPDATE teams
SET organization = ?
WHERE teams.slug = ?
RETURNING id, owner, name, slug, organization
`

type UpdateTeamOrganizationParams struct {
	Organization sql.NullString `db:"organization" json:"organization"`
	Slug         string         `db:"slug" json:"slug"`
}

func (q *Queries) UpdateTeamOrganization(ctx context.Context, arg UpdateTeamOrganizationParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, updateTeamOrganization, arg.Organization, arg.Slug)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Name,
		&i.Slug,
		&i.Organization,
	)
	return i, err
}

const updateTeamOwner = `-- name: UpdateTeamOwner :one
UPDATE teams
SET "owner" = ?
WHERE teams.slug = ?
RETURNING id, owner, name, slug, organization
`

type UpdateTeamOwnerParams struct {
	Owner int64  `db:"owner" json:"owner"`
	Slug  string `db:"slug" json:"slug"`
}

func (q *Queries) UpdateTeamOwner(ctx context.Context, arg UpdateTeamOwnerParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, updateTeamOwner, arg.Owner, arg.Slug)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Name,
		&i.Slug,
		&i.Organization,
	)
	return i, err
}

const updateTournamentDates = `-- name: UpdateTournamentDates :one
UPDATE tournaments
SET "start_date" = ?,
    "end_date" = ?
WHERE id = ?
RETURNING id, team, name, slug, start_date, end_date, location
`

type UpdateTournamentDatesParams struct {
	StartDate    sql.NullTime `db:"start_date" json:"start_date"`
	EndDate      sql.NullTime `db:"end_date" json:"end_date"`
	TournamentId int64        `db:"tournamentId" json:"tournamentId"`
}

func (q *Queries) UpdateTournamentDates(ctx context.Context, arg UpdateTournamentDatesParams) (Tournament, error) {
	row := q.db.QueryRowContext(ctx, updateTournamentDates, arg.StartDate, arg.EndDate, arg.TournamentId)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.Team,
		&i.Name,
		&i.Slug,
		&i.StartDate,
		&i.EndDate,
		&i.Location,
	)
	return i, err
}

const updateTournamentDatumOrder = `-- name: UpdateTournamentDatumOrder :exec
UPDATE tournament_data
SET "order" = ?
WHERE id = ?
    AND tournament = ?
`

type UpdateTournamentDatumOrderParams struct {
	Order        int64 `db:"order" json:"order"`
	DataId       int64 `db:"dataId" json:"dataId"`
	TournamentId int64 `db:"tournamentId" json:"tournamentId"`
}

func (q *Queries) UpdateTournamentDatumOrder(ctx context.Context, arg UpdateTournamentDatumOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateTournamentDatumOrder, arg.Order, arg.DataId, arg.TournamentId)
	return err
}

const updateTournamentLocation = `-- name: UpdateTournamentLocation :one
UPDATE tournaments
SET "location" = ?
WHERE id = ?
RETURNING id, team, name, slug, start_date, end_date, location
`

type UpdateTournamentLocationParams struct {
	Location     sql.NullString `db:"location" json:"location"`
	TournamentId int64          `db:"tournamentId" json:"tournamentId"`
}

func (q *Queries) UpdateTournamentLocation(ctx context.Context, arg UpdateTournamentLocationParams) (Tournament, error) {
	row := q.db.QueryRowContext(ctx, updateTournamentLocation, arg.Location, arg.TournamentId)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.Team,
		&i.Name,
		&i.Slug,
		&i.StartDate,
		&i.EndDate,
		&i.Location,
	)
	return i, err
}
