// Code generated by pb-codegen v0.1 DO NOT EDIT.
package modelspb

import (
    "github.com/pocketbase/pocketbase/tools/types"
    "github.com/pocketbase/pocketbase/models"
)

// Games is a wrapper around models.Record for type safe operations on the collection games.
type Games struct {
    Record *models.Record
}

// GetTournament returns the value of the "tournament" field
// Relation collection related : 1y75qogll4793zz
func (m *Games) GetTournament() string {
    return m.Record.GetString("tournament")
}

// SetTournament sets the value of the "tournament" field
// Relation collection related : 1y75qogll4793zz
func (m *Games) SetTournament(val string)  {
    m.Record.Set("tournament", val)
}

// GetOpponent returns the value of the "opponent" field
func (m *Games) GetOpponent() string {
    return m.Record.GetString("opponent")
}

// SetOpponent sets the value of the "opponent" field
func (m *Games) SetOpponent(val string)  {
    m.Record.Set("opponent", val)
}

// GetTeamScore returns the value of the "team_score" field
func (m *Games) GetTeamScore() int {
    return m.Record.GetInt("team_score")
}

// SetTeamScore sets the value of the "team_score" field
func (m *Games) SetTeamScore(val int)  {
    m.Record.Set("team_score", val)
}

// GetOpponentScore returns the value of the "opponent_score" field
func (m *Games) GetOpponentScore() int {
    return m.Record.GetInt("opponent_score")
}

// SetOpponentScore sets the value of the "opponent_score" field
func (m *Games) SetOpponentScore(val int)  {
    m.Record.Set("opponent_score", val)
}

// GetHalfCap returns the value of the "half_cap" field
func (m *Games) GetHalfCap() int {
    return m.Record.GetInt("half_cap")
}

// SetHalfCap sets the value of the "half_cap" field
func (m *Games) SetHalfCap(val int)  {
    m.Record.Set("half_cap", val)
}

// GetSoftCap returns the value of the "soft_cap" field
func (m *Games) GetSoftCap() int {
    return m.Record.GetInt("soft_cap")
}

// SetSoftCap sets the value of the "soft_cap" field
func (m *Games) SetSoftCap(val int)  {
    m.Record.Set("soft_cap", val)
}

// GetHardCap returns the value of the "hard_cap" field
func (m *Games) GetHardCap() int {
    return m.Record.GetInt("hard_cap")
}

// SetHardCap sets the value of the "hard_cap" field
func (m *Games) SetHardCap(val int)  {
    m.Record.Set("hard_cap", val)
}

// GetWindMph returns the value of the "wind_mph" field
func (m *Games) GetWindMph() int {
    return m.Record.GetInt("wind_mph")
}

// SetWindMph sets the value of the "wind_mph" field
func (m *Games) SetWindMph(val int)  {
    m.Record.Set("wind_mph", val)
}

// GetTempF returns the value of the "temp_f" field
func (m *Games) GetTempF() int {
    return m.Record.GetInt("temp_f")
}

// SetTempF sets the value of the "temp_f" field
func (m *Games) SetTempF(val int)  {
    m.Record.Set("temp_f", val)
}

// GetStartTime returns the value of the "start_time" field
func (m *Games) GetStartTime() types.DateTime {
    return m.Record.GetDateTime("start_time")
}

// SetStartTime sets the value of the "start_time" field
func (m *Games) SetStartTime(val types.DateTime)  {
    m.Record.Set("start_time", val)
}

// GetIsCompleted returns the value of the "is_completed" field
func (m *Games) GetIsCompleted() bool {
    return m.Record.GetBool("is_completed")
}

// SetIsCompleted sets the value of the "is_completed" field
func (m *Games) SetIsCompleted(val bool)  {
    m.Record.Set("is_completed", val)
}
