// Code generated by pb-codegen v0.1 DO NOT EDIT.
package modelspb

import (
    "github.com/pocketbase/pocketbase/models"
)

// PlayerGameSummary is a wrapper around models.Record for type safe operations on the collection player_game_summary.
type PlayerGameSummary struct {
    Record *models.Record
}

// GetPlayerId returns the value of the "player_id" field
// Relation collection related : 873174nlwmcn4sh
func (m *PlayerGameSummary) GetPlayerId() string {
    return m.Record.GetString("player_id")
}

// SetPlayerId sets the value of the "player_id" field
// Relation collection related : 873174nlwmcn4sh
func (m *PlayerGameSummary) SetPlayerId(val string)  {
    m.Record.Set("player_id", val)
}

// GetGameId returns the value of the "game_id" field
// Relation collection related : z10vz6vqnt7cvpg
func (m *PlayerGameSummary) GetGameId() string {
    return m.Record.GetString("game_id")
}

// SetGameId sets the value of the "game_id" field
// Relation collection related : z10vz6vqnt7cvpg
func (m *PlayerGameSummary) SetGameId(val string)  {
    m.Record.Set("game_id", val)
}

// GetTeamId returns the value of the "team_id" field
// Relation collection related : 846ykkxqtaqjxst
func (m *PlayerGameSummary) GetTeamId() string {
    return m.Record.GetString("team_id")
}

// SetTeamId sets the value of the "team_id" field
// Relation collection related : 846ykkxqtaqjxst
func (m *PlayerGameSummary) SetTeamId(val string)  {
    m.Record.Set("team_id", val)
}

// GetPlayerName returns the value of the "player_name" field
func (m *PlayerGameSummary) GetPlayerName() string {
    return m.Record.GetString("player_name")
}

// SetPlayerName sets the value of the "player_name" field
func (m *PlayerGameSummary) SetPlayerName(val string)  {
    m.Record.Set("player_name", val)
}

// GetPoints returns the value of the "points" field
func (m *PlayerGameSummary) GetPoints() int {
    return m.Record.GetInt("points")
}

// SetPoints sets the value of the "points" field
func (m *PlayerGameSummary) SetPoints(val int)  {
    m.Record.Set("points", val)
}

// GetGoals returns the value of the "goals" field
func (m *PlayerGameSummary) GetGoals() int {
    return m.Record.GetInt("goals")
}

// SetGoals sets the value of the "goals" field
func (m *PlayerGameSummary) SetGoals(val int)  {
    m.Record.Set("goals", val)
}

// GetAssists returns the value of the "assists" field
func (m *PlayerGameSummary) GetAssists() int {
    return m.Record.GetInt("assists")
}

// SetAssists sets the value of the "assists" field
func (m *PlayerGameSummary) SetAssists(val int)  {
    m.Record.Set("assists", val)
}

// GetTurns returns the value of the "turns" field
func (m *PlayerGameSummary) GetTurns() int {
    return m.Record.GetInt("turns")
}

// SetTurns sets the value of the "turns" field
func (m *PlayerGameSummary) SetTurns(val int)  {
    m.Record.Set("turns", val)
}

// GetDrops returns the value of the "drops" field
func (m *PlayerGameSummary) GetDrops() int {
    return m.Record.GetInt("drops")
}

// SetDrops sets the value of the "drops" field
func (m *PlayerGameSummary) SetDrops(val int)  {
    m.Record.Set("drops", val)
}
