// Code generated by pb-codegen v0.1 DO NOT EDIT.
package modelspb

import (
    "github.com/pocketbase/pocketbase/models"
)

// PlayerTeamSummary is a wrapper around models.Record for type safe operations on the collection player_team_summary.
type PlayerTeamSummary struct {
    Record *models.Record
}

// GetPlayerId returns the value of the "player_id" field
// Relation collection related : 873174nlwmcn4sh
func (m *PlayerTeamSummary) GetPlayerId() string {
    return m.Record.GetString("player_id")
}

// SetPlayerId sets the value of the "player_id" field
// Relation collection related : 873174nlwmcn4sh
func (m *PlayerTeamSummary) SetPlayerId(val string)  {
    m.Record.Set("player_id", val)
}

// GetTeamId returns the value of the "team_id" field
// Relation collection related : 846ykkxqtaqjxst
func (m *PlayerTeamSummary) GetTeamId() string {
    return m.Record.GetString("team_id")
}

// SetTeamId sets the value of the "team_id" field
// Relation collection related : 846ykkxqtaqjxst
func (m *PlayerTeamSummary) SetTeamId(val string)  {
    m.Record.Set("team_id", val)
}

// GetTeamSlug returns the value of the "team_slug" field
func (m *PlayerTeamSummary) GetTeamSlug() string {
    return m.Record.GetString("team_slug")
}

// SetTeamSlug sets the value of the "team_slug" field
func (m *PlayerTeamSummary) SetTeamSlug(val string)  {
    m.Record.Set("team_slug", val)
}

// GetPlayerName returns the value of the "player_name" field
func (m *PlayerTeamSummary) GetPlayerName() string {
    return m.Record.GetString("player_name")
}

// SetPlayerName sets the value of the "player_name" field
func (m *PlayerTeamSummary) SetPlayerName(val string)  {
    m.Record.Set("player_name", val)
}

// GetPoints returns the value of the "points" field
func (m *PlayerTeamSummary) GetPoints() int {
    return m.Record.GetInt("points")
}

// SetPoints sets the value of the "points" field
func (m *PlayerTeamSummary) SetPoints(val int)  {
    m.Record.Set("points", val)
}

// GetGoals returns the value of the "goals" field
func (m *PlayerTeamSummary) GetGoals() int {
    return m.Record.GetInt("goals")
}

// SetGoals sets the value of the "goals" field
func (m *PlayerTeamSummary) SetGoals(val int)  {
    m.Record.Set("goals", val)
}

// GetAssists returns the value of the "assists" field
func (m *PlayerTeamSummary) GetAssists() int {
    return m.Record.GetInt("assists")
}

// SetAssists sets the value of the "assists" field
func (m *PlayerTeamSummary) SetAssists(val int)  {
    m.Record.Set("assists", val)
}

// GetTurns returns the value of the "turns" field
func (m *PlayerTeamSummary) GetTurns() int {
    return m.Record.GetInt("turns")
}

// SetTurns sets the value of the "turns" field
func (m *PlayerTeamSummary) SetTurns(val int)  {
    m.Record.Set("turns", val)
}

// GetDrops returns the value of the "drops" field
func (m *PlayerTeamSummary) GetDrops() int {
    return m.Record.GetInt("drops")
}

// SetDrops sets the value of the "drops" field
func (m *PlayerTeamSummary) SetDrops(val int)  {
    m.Record.Set("drops", val)
}
