// Code generated by pb-codegen v0.1 DO NOT EDIT.
package modelspb

import (
    "github.com/pocketbase/pocketbase/models"
)

// PlayerTournamentSummary is a wrapper around models.Record for type safe operations on the collection player_tournament_summary.
type PlayerTournamentSummary struct {
    Record *models.Record
}

// GetPlayerId returns the value of the "player_id" field
// Relation collection related : 873174nlwmcn4sh
func (m *PlayerTournamentSummary) GetPlayerId() string {
    return m.Record.GetString("player_id")
}

// SetPlayerId sets the value of the "player_id" field
// Relation collection related : 873174nlwmcn4sh
func (m *PlayerTournamentSummary) SetPlayerId(val string)  {
    m.Record.Set("player_id", val)
}

// GetTournamentId returns the value of the "tournament_id" field
// Relation collection related : 1y75qogll4793zz
func (m *PlayerTournamentSummary) GetTournamentId() string {
    return m.Record.GetString("tournament_id")
}

// SetTournamentId sets the value of the "tournament_id" field
// Relation collection related : 1y75qogll4793zz
func (m *PlayerTournamentSummary) SetTournamentId(val string)  {
    m.Record.Set("tournament_id", val)
}

// GetTeamId returns the value of the "team_id" field
// Relation collection related : 846ykkxqtaqjxst
func (m *PlayerTournamentSummary) GetTeamId() string {
    return m.Record.GetString("team_id")
}

// SetTeamId sets the value of the "team_id" field
// Relation collection related : 846ykkxqtaqjxst
func (m *PlayerTournamentSummary) SetTeamId(val string)  {
    m.Record.Set("team_id", val)
}

// GetPlayerName returns the value of the "player_name" field
func (m *PlayerTournamentSummary) GetPlayerName() string {
    return m.Record.GetString("player_name")
}

// SetPlayerName sets the value of the "player_name" field
func (m *PlayerTournamentSummary) SetPlayerName(val string)  {
    m.Record.Set("player_name", val)
}

// GetPoints returns the value of the "points" field
func (m *PlayerTournamentSummary) GetPoints() int {
    return m.Record.GetInt("points")
}

// SetPoints sets the value of the "points" field
func (m *PlayerTournamentSummary) SetPoints(val int)  {
    m.Record.Set("points", val)
}

// GetGoals returns the value of the "goals" field
func (m *PlayerTournamentSummary) GetGoals() int {
    return m.Record.GetInt("goals")
}

// SetGoals sets the value of the "goals" field
func (m *PlayerTournamentSummary) SetGoals(val int)  {
    m.Record.Set("goals", val)
}

// GetAssists returns the value of the "assists" field
func (m *PlayerTournamentSummary) GetAssists() int {
    return m.Record.GetInt("assists")
}

// SetAssists sets the value of the "assists" field
func (m *PlayerTournamentSummary) SetAssists(val int)  {
    m.Record.Set("assists", val)
}

// GetTurns returns the value of the "turns" field
func (m *PlayerTournamentSummary) GetTurns() int {
    return m.Record.GetInt("turns")
}

// SetTurns sets the value of the "turns" field
func (m *PlayerTournamentSummary) SetTurns(val int)  {
    m.Record.Set("turns", val)
}

// GetDrops returns the value of the "drops" field
func (m *PlayerTournamentSummary) GetDrops() int {
    return m.Record.GetInt("drops")
}

// SetDrops sets the value of the "drops" field
func (m *PlayerTournamentSummary) SetDrops(val int)  {
    m.Record.Set("drops", val)
}
