// Code generated by pb-codegen v0.1 DO NOT EDIT.
package modelspb

import (
    "github.com/pocketbase/pocketbase/models"
)

// Teams is a wrapper around models.Record for type safe operations on the collection teams.
type Teams struct {
    Record *models.Record
}

// GetOrganization returns the value of the "organization" field
func (m *Teams) GetOrganization() string {
    return m.Record.GetString("organization")
}

// SetOrganization sets the value of the "organization" field
func (m *Teams) SetOrganization(val string)  {
    m.Record.Set("organization", val)
}

// GetName returns the value of the "name" field
func (m *Teams) GetName() string {
    return m.Record.GetString("name")
}

// SetName sets the value of the "name" field
func (m *Teams) SetName(val string)  {
    m.Record.Set("name", val)
}

// GetSlug returns the value of the "slug" field
func (m *Teams) GetSlug() string {
    return m.Record.GetString("slug")
}

// SetSlug sets the value of the "slug" field
func (m *Teams) SetSlug(val string)  {
    m.Record.Set("slug", val)
}

// GetManagers returns the value of the "managers" field
// Relation collection related : _pb_users_auth_
func (m *Teams) GetManagers() []string {
    return m.Record.GetStringSlice("managers")
}

// SetManagers sets the value of the "managers" field
// Relation collection related : _pb_users_auth_
func (m *Teams) SetManagers(val []string)  {
    m.Record.Set("managers", val)
}

// GetLogo returns the value of the "logo" field as file
func (m *Teams) GetLogo() string {
    return m.Record.GetString("logo")
}

// SetLogo sets the value of the "logo" field as file
func (m *Teams) SetLogo(val string)  {
    m.Record.Set("logo", val)
}
