// Code generated by pb-codegen v0.1 DO NOT EDIT.
package modelspb

import (
    "github.com/pocketbase/pocketbase/tools/types"
    "github.com/pocketbase/pocketbase/models"
)

// Tournaments is a wrapper around models.Record for type safe operations on the collection tournaments.
type Tournaments struct {
    Record *models.Record
}

// GetTeam returns the value of the "team" field
// Relation collection related : 846ykkxqtaqjxst
func (m *Tournaments) GetTeam() string {
    return m.Record.GetString("team")
}

// SetTeam sets the value of the "team" field
// Relation collection related : 846ykkxqtaqjxst
func (m *Tournaments) SetTeam(val string)  {
    m.Record.Set("team", val)
}

// GetName returns the value of the "name" field
func (m *Tournaments) GetName() string {
    return m.Record.GetString("name")
}

// SetName sets the value of the "name" field
func (m *Tournaments) SetName(val string)  {
    m.Record.Set("name", val)
}

// GetSlug returns the value of the "slug" field
func (m *Tournaments) GetSlug() string {
    return m.Record.GetString("slug")
}

// SetSlug sets the value of the "slug" field
func (m *Tournaments) SetSlug(val string)  {
    m.Record.Set("slug", val)
}

// GetStart returns the value of the "start" field
func (m *Tournaments) GetStart() types.DateTime {
    return m.Record.GetDateTime("start")
}

// SetStart sets the value of the "start" field
func (m *Tournaments) SetStart(val types.DateTime)  {
    m.Record.Set("start", val)
}

// GetEnd returns the value of the "end" field
func (m *Tournaments) GetEnd() types.DateTime {
    return m.Record.GetDateTime("end")
}

// SetEnd sets the value of the "end" field
func (m *Tournaments) SetEnd(val types.DateTime)  {
    m.Record.Set("end", val)
}

// GetLocation returns the value of the "location" field
func (m *Tournaments) GetLocation() string {
    return m.Record.GetString("location")
}

// SetLocation sets the value of the "location" field
func (m *Tournaments) SetLocation(val string)  {
    m.Record.Set("location", val)
}
