root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "sqlc -f ./config/sqlc.yaml generate && templ generate && go build -o ./tmp/main cmd/app/main.go"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "node_modules", "internal/models"]
  exclude_file = []
  exclude_regex = [".*_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "templ", "html", "sql"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true