version: "2"
sql:
  - engine: "sqlite"
    queries: "query.sql"
    schema: "migrations"
    gen:
      go:
        emit_json_tags: true
        emit_db_tags: true
        package: "models"
        out: "../internal/models"