version: "2"
sql:
  - engine: "sqlite"
    queries: "query.sql"
    schema: "migrations"
    gen:
      go:
        emit_json_tags: true
        emit_db_tags: true
        package: "models"
        out: "../internal/models"
        overrides:
          - column: "tournament_data.data_type"
            go_type:
              import: "ultigamecast/internal/models/tournament_data_types"
              type: "Option"
          - column: "games.schedule_status"
            go_type:
              type: "GameScheduleStatus"
          - column: "games.live_status"
            go_type:
              type: "GameLiveStatus"
          - column: "events.previous_game_state"
            go_type:
              type: "GameLiveStatus"
          - column: "events.type"
            go_type:
              type: "EventType"